name: Cache-Clean

on:
  #自动清理：每周一早上4点
  schedule:
    - cron: '0 1 */5 * *'  # UTC 1:00，每5天运行
  #手动清理
  workflow_dispatch:

permissions: write-all
    keep_latest: 3
    keep_min_download_counts: 1 # Optional parameters
    delete_expired_data: 10 # Optional parameters
    delete_tag_pattern: beta # defaults to ""
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
