name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 1 * *'
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@main

      - name: Cache Clean
        run: gh cache delete --all
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0
